### ISSUE TITLE
0.3 Release has broken overcorps

### ISSUE THREAD

**Issue by derwolfe** [RackSec/falcon-mutualauth#2]
Upon running a fresh tox run of overcorps (commit 0ad89c6bd2d61184dde4021042858c7d2cd5aed1), tox fails with a large number of errors (not pasted here, as this is open source repository). These can be replicated by running `tox -r` on a fresh pull of overcorps' master (specifically at the aforementioned commit).

**Comment by ehashman** [comment]
Fixed this with 244236e and the 0.4 release---we had a stray super we missed when turning this into an old-style class.
